// Code generated by protoc-gen-gogo. DO NOT EDIT.
// source: address_count_index.proto

package models

import (
	context "context"
	fmt "fmt"
	
	_ "github.com/infobloxopen/protoc-gen-gorm/options"
	math "math"

	gorm2 "github.com/infobloxopen/atlas-app-toolkit/gorm"
	errors1 "github.com/infobloxopen/protoc-gen-gorm/errors"
	gorm1 "github.com/jinzhu/gorm"
	field_mask1 "google.golang.org/genproto/protobuf/field_mask"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = fmt.Errorf
var _ = math.Inf

type AddressCountIndexORM struct {
	PublicKey string `gorm:"primary_key"`
}

// TableName overrides the default tablename generated by GORM
func (AddressCountIndexORM) TableName() string {
	return "address_count_indices"
}

// ToORM runs the BeforeToORM hook if present, converts the fields of this
// object to ORM format, runs the AfterToORM hook, then returns the ORM object
func (m *AddressCountIndex) ToORM(ctx context.Context) (AddressCountIndexORM, error) {
	to := AddressCountIndexORM{}
	var err error
	if prehook, ok := interface{}(m).(AddressCountIndexWithBeforeToORM); ok {
		if err = prehook.BeforeToORM(ctx, &to); err != nil {
			return to, err
		}
	}
	to.PublicKey = m.PublicKey
	if posthook, ok := interface{}(m).(AddressCountIndexWithAfterToORM); ok {
		err = posthook.AfterToORM(ctx, &to)
	}
	return to, err
}

// ToPB runs the BeforeToPB hook if present, converts the fields of this
// object to PB format, runs the AfterToPB hook, then returns the PB object
func (m *AddressCountIndexORM) ToPB(ctx context.Context) (AddressCountIndex, error) {
	to := AddressCountIndex{}
	var err error
	if prehook, ok := interface{}(m).(AddressCountIndexWithBeforeToPB); ok {
		if err = prehook.BeforeToPB(ctx, &to); err != nil {
			return to, err
		}
	}
	to.PublicKey = m.PublicKey
	if posthook, ok := interface{}(m).(AddressCountIndexWithAfterToPB); ok {
		err = posthook.AfterToPB(ctx, &to)
	}
	return to, err
}

// The following are interfaces you can implement for special behavior during ORM/PB conversions
// of type AddressCountIndex the arg will be the target, the caller the one being converted from

// AddressCountIndexBeforeToORM called before default ToORM code
type AddressCountIndexWithBeforeToORM interface {
	BeforeToORM(context.Context, *AddressCountIndexORM) error
}

// AddressCountIndexAfterToORM called after default ToORM code
type AddressCountIndexWithAfterToORM interface {
	AfterToORM(context.Context, *AddressCountIndexORM) error
}

// AddressCountIndexBeforeToPB called before default ToPB code
type AddressCountIndexWithBeforeToPB interface {
	BeforeToPB(context.Context, *AddressCountIndex) error
}

// AddressCountIndexAfterToPB called after default ToPB code
type AddressCountIndexWithAfterToPB interface {
	AfterToPB(context.Context, *AddressCountIndex) error
}

// DefaultCreateAddressCountIndex executes a basic gorm create call
func DefaultCreateAddressCountIndex(ctx context.Context, in *AddressCountIndex, db *gorm1.DB) (*AddressCountIndex, error) {
	if in == nil {
		return nil, errors1.NilArgumentError
	}
	ormObj, err := in.ToORM(ctx)
	if err != nil {
		return nil, err
	}
	if hook, ok := interface{}(&ormObj).(AddressCountIndexORMWithBeforeCreate_); ok {
		if db, err = hook.BeforeCreate_(ctx, db); err != nil {
			return nil, err
		}
	}
	if err = db.Create(&ormObj).Error; err != nil {
		return nil, err
	}
	if hook, ok := interface{}(&ormObj).(AddressCountIndexORMWithAfterCreate_); ok {
		if err = hook.AfterCreate_(ctx, db); err != nil {
			return nil, err
		}
	}
	pbResponse, err := ormObj.ToPB(ctx)
	return &pbResponse, err
}

type AddressCountIndexORMWithBeforeCreate_ interface {
	BeforeCreate_(context.Context, *gorm1.DB) (*gorm1.DB, error)
}
type AddressCountIndexORMWithAfterCreate_ interface {
	AfterCreate_(context.Context, *gorm1.DB) error
}

// DefaultApplyFieldMaskAddressCountIndex patches an pbObject with patcher according to a field mask.
func DefaultApplyFieldMaskAddressCountIndex(ctx context.Context, patchee *AddressCountIndex, patcher *AddressCountIndex, updateMask *field_mask1.FieldMask, prefix string, db *gorm1.DB) (*AddressCountIndex, error) {
	if patcher == nil {
		return nil, nil
	} else if patchee == nil {
		return nil, errors1.NilArgumentError
	}
	var err error
	for _, f := range updateMask.Paths {
		if f == prefix+"PublicKey" {
			patchee.PublicKey = patcher.PublicKey
			continue
		}
	}
	if err != nil {
		return nil, err
	}
	return patchee, nil
}

// DefaultListAddressCountIndex executes a gorm list call
func DefaultListAddressCountIndex(ctx context.Context, db *gorm1.DB) ([]*AddressCountIndex, error) {
	in := AddressCountIndex{}
	ormObj, err := in.ToORM(ctx)
	if err != nil {
		return nil, err
	}
	if hook, ok := interface{}(&ormObj).(AddressCountIndexORMWithBeforeListApplyQuery); ok {
		if db, err = hook.BeforeListApplyQuery(ctx, db); err != nil {
			return nil, err
		}
	}
	db, err = gorm2.ApplyCollectionOperators(ctx, db, &AddressCountIndexORM{}, &AddressCountIndex{}, nil, nil, nil, nil)
	if err != nil {
		return nil, err
	}
	if hook, ok := interface{}(&ormObj).(AddressCountIndexORMWithBeforeListFind); ok {
		if db, err = hook.BeforeListFind(ctx, db); err != nil {
			return nil, err
		}
	}
	db = db.Where(&ormObj)
	db = db.Order("public_key")
	ormResponse := []AddressCountIndexORM{}
	if err := db.Find(&ormResponse).Error; err != nil {
		return nil, err
	}
	if hook, ok := interface{}(&ormObj).(AddressCountIndexORMWithAfterListFind); ok {
		if err = hook.AfterListFind(ctx, db, &ormResponse); err != nil {
			return nil, err
		}
	}
	pbResponse := []*AddressCountIndex{}
	for _, responseEntry := range ormResponse {
		temp, err := responseEntry.ToPB(ctx)
		if err != nil {
			return nil, err
		}
		pbResponse = append(pbResponse, &temp)
	}
	return pbResponse, nil
}

type AddressCountIndexORMWithBeforeListApplyQuery interface {
	BeforeListApplyQuery(context.Context, *gorm1.DB) (*gorm1.DB, error)
}
type AddressCountIndexORMWithBeforeListFind interface {
	BeforeListFind(context.Context, *gorm1.DB) (*gorm1.DB, error)
}
type AddressCountIndexORMWithAfterListFind interface {
	AfterListFind(context.Context, *gorm1.DB, *[]AddressCountIndexORM) error
}
