// Code generated by protoc-gen-gogo. DO NOT EDIT.
// source: address_count.proto

package models

import (
	context "context"
	fmt "fmt"
	
	_ "github.com/infobloxopen/protoc-gen-gorm/options"
	math "math"

	gorm2 "github.com/infobloxopen/atlas-app-toolkit/gorm"
	errors1 "github.com/infobloxopen/protoc-gen-gorm/errors"
	gorm1 "github.com/jinzhu/gorm"
	field_mask1 "google.golang.org/genproto/protobuf/field_mask"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = fmt.Errorf
var _ = math.Inf

type AddressCountORM struct {
	Count     uint64
	PublicKey string `gorm:"index:address_count_idx_public_key"`
	Type      string `gorm:"primary_key"`
}

// TableName overrides the default tablename generated by GORM
func (AddressCountORM) TableName() string {
	return "address_counts"
}

// ToORM runs the BeforeToORM hook if present, converts the fields of this
// object to ORM format, runs the AfterToORM hook, then returns the ORM object
func (m *AddressCount) ToORM(ctx context.Context) (AddressCountORM, error) {
	to := AddressCountORM{}
	var err error
	if prehook, ok := interface{}(m).(AddressCountWithBeforeToORM); ok {
		if err = prehook.BeforeToORM(ctx, &to); err != nil {
			return to, err
		}
	}
	to.Type = m.Type
	to.Count = m.Count
	to.PublicKey = m.PublicKey
	if posthook, ok := interface{}(m).(AddressCountWithAfterToORM); ok {
		err = posthook.AfterToORM(ctx, &to)
	}
	return to, err
}

// ToPB runs the BeforeToPB hook if present, converts the fields of this
// object to PB format, runs the AfterToPB hook, then returns the PB object
func (m *AddressCountORM) ToPB(ctx context.Context) (AddressCount, error) {
	to := AddressCount{}
	var err error
	if prehook, ok := interface{}(m).(AddressCountWithBeforeToPB); ok {
		if err = prehook.BeforeToPB(ctx, &to); err != nil {
			return to, err
		}
	}
	to.Type = m.Type
	to.Count = m.Count
	to.PublicKey = m.PublicKey
	if posthook, ok := interface{}(m).(AddressCountWithAfterToPB); ok {
		err = posthook.AfterToPB(ctx, &to)
	}
	return to, err
}

// The following are interfaces you can implement for special behavior during ORM/PB conversions
// of type AddressCount the arg will be the target, the caller the one being converted from

// AddressCountBeforeToORM called before default ToORM code
type AddressCountWithBeforeToORM interface {
	BeforeToORM(context.Context, *AddressCountORM) error
}

// AddressCountAfterToORM called after default ToORM code
type AddressCountWithAfterToORM interface {
	AfterToORM(context.Context, *AddressCountORM) error
}

// AddressCountBeforeToPB called before default ToPB code
type AddressCountWithBeforeToPB interface {
	BeforeToPB(context.Context, *AddressCount) error
}

// AddressCountAfterToPB called after default ToPB code
type AddressCountWithAfterToPB interface {
	AfterToPB(context.Context, *AddressCount) error
}

// DefaultCreateAddressCount executes a basic gorm create call
func DefaultCreateAddressCount(ctx context.Context, in *AddressCount, db *gorm1.DB) (*AddressCount, error) {
	if in == nil {
		return nil, errors1.NilArgumentError
	}
	ormObj, err := in.ToORM(ctx)
	if err != nil {
		return nil, err
	}
	if hook, ok := interface{}(&ormObj).(AddressCountORMWithBeforeCreate_); ok {
		if db, err = hook.BeforeCreate_(ctx, db); err != nil {
			return nil, err
		}
	}
	if err = db.Create(&ormObj).Error; err != nil {
		return nil, err
	}
	if hook, ok := interface{}(&ormObj).(AddressCountORMWithAfterCreate_); ok {
		if err = hook.AfterCreate_(ctx, db); err != nil {
			return nil, err
		}
	}
	pbResponse, err := ormObj.ToPB(ctx)
	return &pbResponse, err
}

type AddressCountORMWithBeforeCreate_ interface {
	BeforeCreate_(context.Context, *gorm1.DB) (*gorm1.DB, error)
}
type AddressCountORMWithAfterCreate_ interface {
	AfterCreate_(context.Context, *gorm1.DB) error
}

// DefaultApplyFieldMaskAddressCount patches an pbObject with patcher according to a field mask.
func DefaultApplyFieldMaskAddressCount(ctx context.Context, patchee *AddressCount, patcher *AddressCount, updateMask *field_mask1.FieldMask, prefix string, db *gorm1.DB) (*AddressCount, error) {
	if patcher == nil {
		return nil, nil
	} else if patchee == nil {
		return nil, errors1.NilArgumentError
	}
	var err error
	for _, f := range updateMask.Paths {
		if f == prefix+"Type" {
			patchee.Type = patcher.Type
			continue
		}
		if f == prefix+"Count" {
			patchee.Count = patcher.Count
			continue
		}
		if f == prefix+"PublicKey" {
			patchee.PublicKey = patcher.PublicKey
			continue
		}
	}
	if err != nil {
		return nil, err
	}
	return patchee, nil
}

// DefaultListAddressCount executes a gorm list call
func DefaultListAddressCount(ctx context.Context, db *gorm1.DB) ([]*AddressCount, error) {
	in := AddressCount{}
	ormObj, err := in.ToORM(ctx)
	if err != nil {
		return nil, err
	}
	if hook, ok := interface{}(&ormObj).(AddressCountORMWithBeforeListApplyQuery); ok {
		if db, err = hook.BeforeListApplyQuery(ctx, db); err != nil {
			return nil, err
		}
	}
	db, err = gorm2.ApplyCollectionOperators(ctx, db, &AddressCountORM{}, &AddressCount{}, nil, nil, nil, nil)
	if err != nil {
		return nil, err
	}
	if hook, ok := interface{}(&ormObj).(AddressCountORMWithBeforeListFind); ok {
		if db, err = hook.BeforeListFind(ctx, db); err != nil {
			return nil, err
		}
	}
	db = db.Where(&ormObj)
	db = db.Order("type")
	ormResponse := []AddressCountORM{}
	if err := db.Find(&ormResponse).Error; err != nil {
		return nil, err
	}
	if hook, ok := interface{}(&ormObj).(AddressCountORMWithAfterListFind); ok {
		if err = hook.AfterListFind(ctx, db, &ormResponse); err != nil {
			return nil, err
		}
	}
	pbResponse := []*AddressCount{}
	for _, responseEntry := range ormResponse {
		temp, err := responseEntry.ToPB(ctx)
		if err != nil {
			return nil, err
		}
		pbResponse = append(pbResponse, &temp)
	}
	return pbResponse, nil
}

type AddressCountORMWithBeforeListApplyQuery interface {
	BeforeListApplyQuery(context.Context, *gorm1.DB) (*gorm1.DB, error)
}
type AddressCountORMWithBeforeListFind interface {
	BeforeListFind(context.Context, *gorm1.DB) (*gorm1.DB, error)
}
type AddressCountORMWithAfterListFind interface {
	AfterListFind(context.Context, *gorm1.DB, *[]AddressCountORM) error
}
