// Code generated by protoc-gen-gogo. DO NOT EDIT.
// source: address_token_count_index.proto

package models

import (
	context "context"
	fmt "fmt"
	
	_ "github.com/infobloxopen/protoc-gen-gorm/options"
	math "math"

	gorm2 "github.com/infobloxopen/atlas-app-toolkit/gorm"
	errors1 "github.com/infobloxopen/protoc-gen-gorm/errors"
	gorm1 "github.com/jinzhu/gorm"
	field_mask1 "google.golang.org/genproto/protobuf/field_mask"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = fmt.Errorf
var _ = math.Inf

type AddressTokenCountIndexORM struct {
	PublicKey string `gorm:"primary_key"`
}

// TableName overrides the default tablename generated by GORM
func (AddressTokenCountIndexORM) TableName() string {
	return "address_token_count_indices"
}

// ToORM runs the BeforeToORM hook if present, converts the fields of this
// object to ORM format, runs the AfterToORM hook, then returns the ORM object
func (m *AddressTokenCountIndex) ToORM(ctx context.Context) (AddressTokenCountIndexORM, error) {
	to := AddressTokenCountIndexORM{}
	var err error
	if prehook, ok := interface{}(m).(AddressTokenCountIndexWithBeforeToORM); ok {
		if err = prehook.BeforeToORM(ctx, &to); err != nil {
			return to, err
		}
	}
	to.PublicKey = m.PublicKey
	if posthook, ok := interface{}(m).(AddressTokenCountIndexWithAfterToORM); ok {
		err = posthook.AfterToORM(ctx, &to)
	}
	return to, err
}

// ToPB runs the BeforeToPB hook if present, converts the fields of this
// object to PB format, runs the AfterToPB hook, then returns the PB object
func (m *AddressTokenCountIndexORM) ToPB(ctx context.Context) (AddressTokenCountIndex, error) {
	to := AddressTokenCountIndex{}
	var err error
	if prehook, ok := interface{}(m).(AddressTokenCountIndexWithBeforeToPB); ok {
		if err = prehook.BeforeToPB(ctx, &to); err != nil {
			return to, err
		}
	}
	to.PublicKey = m.PublicKey
	if posthook, ok := interface{}(m).(AddressTokenCountIndexWithAfterToPB); ok {
		err = posthook.AfterToPB(ctx, &to)
	}
	return to, err
}

// The following are interfaces you can implement for special behavior during ORM/PB conversions
// of type AddressTokenCountIndex the arg will be the target, the caller the one being converted from

// AddressTokenCountIndexBeforeToORM called before default ToORM code
type AddressTokenCountIndexWithBeforeToORM interface {
	BeforeToORM(context.Context, *AddressTokenCountIndexORM) error
}

// AddressTokenCountIndexAfterToORM called after default ToORM code
type AddressTokenCountIndexWithAfterToORM interface {
	AfterToORM(context.Context, *AddressTokenCountIndexORM) error
}

// AddressTokenCountIndexBeforeToPB called before default ToPB code
type AddressTokenCountIndexWithBeforeToPB interface {
	BeforeToPB(context.Context, *AddressTokenCountIndex) error
}

// AddressTokenCountIndexAfterToPB called after default ToPB code
type AddressTokenCountIndexWithAfterToPB interface {
	AfterToPB(context.Context, *AddressTokenCountIndex) error
}

// DefaultCreateAddressTokenCountIndex executes a basic gorm create call
func DefaultCreateAddressTokenCountIndex(ctx context.Context, in *AddressTokenCountIndex, db *gorm1.DB) (*AddressTokenCountIndex, error) {
	if in == nil {
		return nil, errors1.NilArgumentError
	}
	ormObj, err := in.ToORM(ctx)
	if err != nil {
		return nil, err
	}
	if hook, ok := interface{}(&ormObj).(AddressTokenCountIndexORMWithBeforeCreate_); ok {
		if db, err = hook.BeforeCreate_(ctx, db); err != nil {
			return nil, err
		}
	}
	if err = db.Create(&ormObj).Error; err != nil {
		return nil, err
	}
	if hook, ok := interface{}(&ormObj).(AddressTokenCountIndexORMWithAfterCreate_); ok {
		if err = hook.AfterCreate_(ctx, db); err != nil {
			return nil, err
		}
	}
	pbResponse, err := ormObj.ToPB(ctx)
	return &pbResponse, err
}

type AddressTokenCountIndexORMWithBeforeCreate_ interface {
	BeforeCreate_(context.Context, *gorm1.DB) (*gorm1.DB, error)
}
type AddressTokenCountIndexORMWithAfterCreate_ interface {
	AfterCreate_(context.Context, *gorm1.DB) error
}

// DefaultApplyFieldMaskAddressTokenCountIndex patches an pbObject with patcher according to a field mask.
func DefaultApplyFieldMaskAddressTokenCountIndex(ctx context.Context, patchee *AddressTokenCountIndex, patcher *AddressTokenCountIndex, updateMask *field_mask1.FieldMask, prefix string, db *gorm1.DB) (*AddressTokenCountIndex, error) {
	if patcher == nil {
		return nil, nil
	} else if patchee == nil {
		return nil, errors1.NilArgumentError
	}
	var err error
	for _, f := range updateMask.Paths {
		if f == prefix+"PublicKey" {
			patchee.PublicKey = patcher.PublicKey
			continue
		}
	}
	if err != nil {
		return nil, err
	}
	return patchee, nil
}

// DefaultListAddressTokenCountIndex executes a gorm list call
func DefaultListAddressTokenCountIndex(ctx context.Context, db *gorm1.DB) ([]*AddressTokenCountIndex, error) {
	in := AddressTokenCountIndex{}
	ormObj, err := in.ToORM(ctx)
	if err != nil {
		return nil, err
	}
	if hook, ok := interface{}(&ormObj).(AddressTokenCountIndexORMWithBeforeListApplyQuery); ok {
		if db, err = hook.BeforeListApplyQuery(ctx, db); err != nil {
			return nil, err
		}
	}
	db, err = gorm2.ApplyCollectionOperators(ctx, db, &AddressTokenCountIndexORM{}, &AddressTokenCountIndex{}, nil, nil, nil, nil)
	if err != nil {
		return nil, err
	}
	if hook, ok := interface{}(&ormObj).(AddressTokenCountIndexORMWithBeforeListFind); ok {
		if db, err = hook.BeforeListFind(ctx, db); err != nil {
			return nil, err
		}
	}
	db = db.Where(&ormObj)
	db = db.Order("public_key")
	ormResponse := []AddressTokenCountIndexORM{}
	if err := db.Find(&ormResponse).Error; err != nil {
		return nil, err
	}
	if hook, ok := interface{}(&ormObj).(AddressTokenCountIndexORMWithAfterListFind); ok {
		if err = hook.AfterListFind(ctx, db, &ormResponse); err != nil {
			return nil, err
		}
	}
	pbResponse := []*AddressTokenCountIndex{}
	for _, responseEntry := range ormResponse {
		temp, err := responseEntry.ToPB(ctx)
		if err != nil {
			return nil, err
		}
		pbResponse = append(pbResponse, &temp)
	}
	return pbResponse, nil
}

type AddressTokenCountIndexORMWithBeforeListApplyQuery interface {
	BeforeListApplyQuery(context.Context, *gorm1.DB) (*gorm1.DB, error)
}
type AddressTokenCountIndexORMWithBeforeListFind interface {
	BeforeListFind(context.Context, *gorm1.DB) (*gorm1.DB, error)
}
type AddressTokenCountIndexORMWithAfterListFind interface {
	AfterListFind(context.Context, *gorm1.DB, *[]AddressTokenCountIndexORM) error
}
