// Code generated by protoc-gen-gogo. DO NOT EDIT.
// source: balance.proto

package models

import (
	context "context"
	fmt "fmt"
	
	_ "github.com/infobloxopen/protoc-gen-gorm/options"
	math "math"

	gorm2 "github.com/infobloxopen/atlas-app-toolkit/gorm"
	errors1 "github.com/infobloxopen/protoc-gen-gorm/errors"
	gorm1 "github.com/jinzhu/gorm"
	field_mask1 "google.golang.org/genproto/protobuf/field_mask"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = fmt.Errorf
var _ = math.Inf

type BalanceORM struct {
	BlockNumber      uint64 `gorm:"primary_key"`
	LogIndex         int32  `gorm:"primary_key"`
	PublicKey        string `gorm:"primary_key"`
	Timestamp        uint64 `gorm:"index:balance_idx_timestamp"`
	TransactionIndex uint32 `gorm:"primary_key"`
	Value            string
	ValueDecimal     float64
}

// TableName overrides the default tablename generated by GORM
func (BalanceORM) TableName() string {
	return "balances"
}

// ToORM runs the BeforeToORM hook if present, converts the fields of this
// object to ORM format, runs the AfterToORM hook, then returns the ORM object
func (m *Balance) ToORM(ctx context.Context) (BalanceORM, error) {
	to := BalanceORM{}
	var err error
	if prehook, ok := interface{}(m).(BalanceWithBeforeToORM); ok {
		if err = prehook.BeforeToORM(ctx, &to); err != nil {
			return to, err
		}
	}
	to.BlockNumber = m.BlockNumber
	to.TransactionIndex = m.TransactionIndex
	to.LogIndex = m.LogIndex
	to.PublicKey = m.PublicKey
	to.Value = m.Value
	to.ValueDecimal = m.ValueDecimal
	to.Timestamp = m.Timestamp
	if posthook, ok := interface{}(m).(BalanceWithAfterToORM); ok {
		err = posthook.AfterToORM(ctx, &to)
	}
	return to, err
}

// ToPB runs the BeforeToPB hook if present, converts the fields of this
// object to PB format, runs the AfterToPB hook, then returns the PB object
func (m *BalanceORM) ToPB(ctx context.Context) (Balance, error) {
	to := Balance{}
	var err error
	if prehook, ok := interface{}(m).(BalanceWithBeforeToPB); ok {
		if err = prehook.BeforeToPB(ctx, &to); err != nil {
			return to, err
		}
	}
	to.BlockNumber = m.BlockNumber
	to.TransactionIndex = m.TransactionIndex
	to.LogIndex = m.LogIndex
	to.PublicKey = m.PublicKey
	to.Value = m.Value
	to.ValueDecimal = m.ValueDecimal
	to.Timestamp = m.Timestamp
	if posthook, ok := interface{}(m).(BalanceWithAfterToPB); ok {
		err = posthook.AfterToPB(ctx, &to)
	}
	return to, err
}

// The following are interfaces you can implement for special behavior during ORM/PB conversions
// of type Balance the arg will be the target, the caller the one being converted from

// BalanceBeforeToORM called before default ToORM code
type BalanceWithBeforeToORM interface {
	BeforeToORM(context.Context, *BalanceORM) error
}

// BalanceAfterToORM called after default ToORM code
type BalanceWithAfterToORM interface {
	AfterToORM(context.Context, *BalanceORM) error
}

// BalanceBeforeToPB called before default ToPB code
type BalanceWithBeforeToPB interface {
	BeforeToPB(context.Context, *Balance) error
}

// BalanceAfterToPB called after default ToPB code
type BalanceWithAfterToPB interface {
	AfterToPB(context.Context, *Balance) error
}

// DefaultCreateBalance executes a basic gorm create call
func DefaultCreateBalance(ctx context.Context, in *Balance, db *gorm1.DB) (*Balance, error) {
	if in == nil {
		return nil, errors1.NilArgumentError
	}
	ormObj, err := in.ToORM(ctx)
	if err != nil {
		return nil, err
	}
	if hook, ok := interface{}(&ormObj).(BalanceORMWithBeforeCreate_); ok {
		if db, err = hook.BeforeCreate_(ctx, db); err != nil {
			return nil, err
		}
	}
	if err = db.Create(&ormObj).Error; err != nil {
		return nil, err
	}
	if hook, ok := interface{}(&ormObj).(BalanceORMWithAfterCreate_); ok {
		if err = hook.AfterCreate_(ctx, db); err != nil {
			return nil, err
		}
	}
	pbResponse, err := ormObj.ToPB(ctx)
	return &pbResponse, err
}

type BalanceORMWithBeforeCreate_ interface {
	BeforeCreate_(context.Context, *gorm1.DB) (*gorm1.DB, error)
}
type BalanceORMWithAfterCreate_ interface {
	AfterCreate_(context.Context, *gorm1.DB) error
}

// DefaultApplyFieldMaskBalance patches an pbObject with patcher according to a field mask.
func DefaultApplyFieldMaskBalance(ctx context.Context, patchee *Balance, patcher *Balance, updateMask *field_mask1.FieldMask, prefix string, db *gorm1.DB) (*Balance, error) {
	if patcher == nil {
		return nil, nil
	} else if patchee == nil {
		return nil, errors1.NilArgumentError
	}
	var err error
	for _, f := range updateMask.Paths {
		if f == prefix+"BlockNumber" {
			patchee.BlockNumber = patcher.BlockNumber
			continue
		}
		if f == prefix+"TransactionIndex" {
			patchee.TransactionIndex = patcher.TransactionIndex
			continue
		}
		if f == prefix+"LogIndex" {
			patchee.LogIndex = patcher.LogIndex
			continue
		}
		if f == prefix+"PublicKey" {
			patchee.PublicKey = patcher.PublicKey
			continue
		}
		if f == prefix+"Value" {
			patchee.Value = patcher.Value
			continue
		}
		if f == prefix+"ValueDecimal" {
			patchee.ValueDecimal = patcher.ValueDecimal
			continue
		}
		if f == prefix+"Timestamp" {
			patchee.Timestamp = patcher.Timestamp
			continue
		}
	}
	if err != nil {
		return nil, err
	}
	return patchee, nil
}

// DefaultListBalance executes a gorm list call
func DefaultListBalance(ctx context.Context, db *gorm1.DB) ([]*Balance, error) {
	in := Balance{}
	ormObj, err := in.ToORM(ctx)
	if err != nil {
		return nil, err
	}
	if hook, ok := interface{}(&ormObj).(BalanceORMWithBeforeListApplyQuery); ok {
		if db, err = hook.BeforeListApplyQuery(ctx, db); err != nil {
			return nil, err
		}
	}
	db, err = gorm2.ApplyCollectionOperators(ctx, db, &BalanceORM{}, &Balance{}, nil, nil, nil, nil)
	if err != nil {
		return nil, err
	}
	if hook, ok := interface{}(&ormObj).(BalanceORMWithBeforeListFind); ok {
		if db, err = hook.BeforeListFind(ctx, db); err != nil {
			return nil, err
		}
	}
	db = db.Where(&ormObj)
	db = db.Order("block_number")
	ormResponse := []BalanceORM{}
	if err := db.Find(&ormResponse).Error; err != nil {
		return nil, err
	}
	if hook, ok := interface{}(&ormObj).(BalanceORMWithAfterListFind); ok {
		if err = hook.AfterListFind(ctx, db, &ormResponse); err != nil {
			return nil, err
		}
	}
	pbResponse := []*Balance{}
	for _, responseEntry := range ormResponse {
		temp, err := responseEntry.ToPB(ctx)
		if err != nil {
			return nil, err
		}
		pbResponse = append(pbResponse, &temp)
	}
	return pbResponse, nil
}

type BalanceORMWithBeforeListApplyQuery interface {
	BeforeListApplyQuery(context.Context, *gorm1.DB) (*gorm1.DB, error)
}
type BalanceORMWithBeforeListFind interface {
	BeforeListFind(context.Context, *gorm1.DB) (*gorm1.DB, error)
}
type BalanceORMWithAfterListFind interface {
	AfterListFind(context.Context, *gorm1.DB, *[]BalanceORM) error
}
