// Code generated by protoc-gen-gogo. DO NOT EDIT.
// source: contract_processed.proto

package models

import (
	context "context"
	fmt "fmt"
	
	_ "github.com/infobloxopen/protoc-gen-gorm/options"
	math "math"

	gorm2 "github.com/infobloxopen/atlas-app-toolkit/gorm"
	errors1 "github.com/infobloxopen/protoc-gen-gorm/errors"
	gorm1 "github.com/jinzhu/gorm"
	field_mask1 "google.golang.org/genproto/protobuf/field_mask"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = fmt.Errorf
var _ = math.Inf

type ContractProcessedORM struct {
	Address          string `gorm:"primary_key"`
	CreatedTimestamp int64  `gorm:"index:contract_processed_idx_created_timestamp"`
	IsToken          bool   `gorm:"index:contract_processed_idx_is_token"`
	Name             string
	Status           string
}

// TableName overrides the default tablename generated by GORM
func (ContractProcessedORM) TableName() string {
	return "contract_processeds"
}

// ToORM runs the BeforeToORM hook if present, converts the fields of this
// object to ORM format, runs the AfterToORM hook, then returns the ORM object
func (m *ContractProcessed) ToORM(ctx context.Context) (ContractProcessedORM, error) {
	to := ContractProcessedORM{}
	var err error
	if prehook, ok := interface{}(m).(ContractProcessedWithBeforeToORM); ok {
		if err = prehook.BeforeToORM(ctx, &to); err != nil {
			return to, err
		}
	}
	to.Address = m.Address
	to.Name = m.Name
	to.CreatedTimestamp = m.CreatedTimestamp
	to.Status = m.Status
	to.IsToken = m.IsToken
	if posthook, ok := interface{}(m).(ContractProcessedWithAfterToORM); ok {
		err = posthook.AfterToORM(ctx, &to)
	}
	return to, err
}

// ToPB runs the BeforeToPB hook if present, converts the fields of this
// object to PB format, runs the AfterToPB hook, then returns the PB object
func (m *ContractProcessedORM) ToPB(ctx context.Context) (ContractProcessed, error) {
	to := ContractProcessed{}
	var err error
	if prehook, ok := interface{}(m).(ContractProcessedWithBeforeToPB); ok {
		if err = prehook.BeforeToPB(ctx, &to); err != nil {
			return to, err
		}
	}
	to.Address = m.Address
	to.Name = m.Name
	to.CreatedTimestamp = m.CreatedTimestamp
	to.Status = m.Status
	to.IsToken = m.IsToken
	if posthook, ok := interface{}(m).(ContractProcessedWithAfterToPB); ok {
		err = posthook.AfterToPB(ctx, &to)
	}
	return to, err
}

// The following are interfaces you can implement for special behavior during ORM/PB conversions
// of type ContractProcessed the arg will be the target, the caller the one being converted from

// ContractProcessedBeforeToORM called before default ToORM code
type ContractProcessedWithBeforeToORM interface {
	BeforeToORM(context.Context, *ContractProcessedORM) error
}

// ContractProcessedAfterToORM called after default ToORM code
type ContractProcessedWithAfterToORM interface {
	AfterToORM(context.Context, *ContractProcessedORM) error
}

// ContractProcessedBeforeToPB called before default ToPB code
type ContractProcessedWithBeforeToPB interface {
	BeforeToPB(context.Context, *ContractProcessed) error
}

// ContractProcessedAfterToPB called after default ToPB code
type ContractProcessedWithAfterToPB interface {
	AfterToPB(context.Context, *ContractProcessed) error
}

// DefaultCreateContractProcessed executes a basic gorm create call
func DefaultCreateContractProcessed(ctx context.Context, in *ContractProcessed, db *gorm1.DB) (*ContractProcessed, error) {
	if in == nil {
		return nil, errors1.NilArgumentError
	}
	ormObj, err := in.ToORM(ctx)
	if err != nil {
		return nil, err
	}
	if hook, ok := interface{}(&ormObj).(ContractProcessedORMWithBeforeCreate_); ok {
		if db, err = hook.BeforeCreate_(ctx, db); err != nil {
			return nil, err
		}
	}
	if err = db.Create(&ormObj).Error; err != nil {
		return nil, err
	}
	if hook, ok := interface{}(&ormObj).(ContractProcessedORMWithAfterCreate_); ok {
		if err = hook.AfterCreate_(ctx, db); err != nil {
			return nil, err
		}
	}
	pbResponse, err := ormObj.ToPB(ctx)
	return &pbResponse, err
}

type ContractProcessedORMWithBeforeCreate_ interface {
	BeforeCreate_(context.Context, *gorm1.DB) (*gorm1.DB, error)
}
type ContractProcessedORMWithAfterCreate_ interface {
	AfterCreate_(context.Context, *gorm1.DB) error
}

// DefaultApplyFieldMaskContractProcessed patches an pbObject with patcher according to a field mask.
func DefaultApplyFieldMaskContractProcessed(ctx context.Context, patchee *ContractProcessed, patcher *ContractProcessed, updateMask *field_mask1.FieldMask, prefix string, db *gorm1.DB) (*ContractProcessed, error) {
	if patcher == nil {
		return nil, nil
	} else if patchee == nil {
		return nil, errors1.NilArgumentError
	}
	var err error
	for _, f := range updateMask.Paths {
		if f == prefix+"Address" {
			patchee.Address = patcher.Address
			continue
		}
		if f == prefix+"Name" {
			patchee.Name = patcher.Name
			continue
		}
		if f == prefix+"CreatedTimestamp" {
			patchee.CreatedTimestamp = patcher.CreatedTimestamp
			continue
		}
		if f == prefix+"Status" {
			patchee.Status = patcher.Status
			continue
		}
		if f == prefix+"IsToken" {
			patchee.IsToken = patcher.IsToken
			continue
		}
	}
	if err != nil {
		return nil, err
	}
	return patchee, nil
}

// DefaultListContractProcessed executes a gorm list call
func DefaultListContractProcessed(ctx context.Context, db *gorm1.DB) ([]*ContractProcessed, error) {
	in := ContractProcessed{}
	ormObj, err := in.ToORM(ctx)
	if err != nil {
		return nil, err
	}
	if hook, ok := interface{}(&ormObj).(ContractProcessedORMWithBeforeListApplyQuery); ok {
		if db, err = hook.BeforeListApplyQuery(ctx, db); err != nil {
			return nil, err
		}
	}
	db, err = gorm2.ApplyCollectionOperators(ctx, db, &ContractProcessedORM{}, &ContractProcessed{}, nil, nil, nil, nil)
	if err != nil {
		return nil, err
	}
	if hook, ok := interface{}(&ormObj).(ContractProcessedORMWithBeforeListFind); ok {
		if db, err = hook.BeforeListFind(ctx, db); err != nil {
			return nil, err
		}
	}
	db = db.Where(&ormObj)
	db = db.Order("address")
	ormResponse := []ContractProcessedORM{}
	if err := db.Find(&ormResponse).Error; err != nil {
		return nil, err
	}
	if hook, ok := interface{}(&ormObj).(ContractProcessedORMWithAfterListFind); ok {
		if err = hook.AfterListFind(ctx, db, &ormResponse); err != nil {
			return nil, err
		}
	}
	pbResponse := []*ContractProcessed{}
	for _, responseEntry := range ormResponse {
		temp, err := responseEntry.ToPB(ctx)
		if err != nil {
			return nil, err
		}
		pbResponse = append(pbResponse, &temp)
	}
	return pbResponse, nil
}

type ContractProcessedORMWithBeforeListApplyQuery interface {
	BeforeListApplyQuery(context.Context, *gorm1.DB) (*gorm1.DB, error)
}
type ContractProcessedORMWithBeforeListFind interface {
	BeforeListFind(context.Context, *gorm1.DB) (*gorm1.DB, error)
}
type ContractProcessedORMWithAfterListFind interface {
	AfterListFind(context.Context, *gorm1.DB, *[]ContractProcessedORM) error
}
