// Code generated by protoc-gen-gogo. DO NOT EDIT.
// source: governance_prep_processed.proto

package models

import (
	context "context"
	fmt "fmt"
	
	_ "github.com/infobloxopen/protoc-gen-gorm/options"
	math "math"

	gorm2 "github.com/infobloxopen/atlas-app-toolkit/gorm"
	errors1 "github.com/infobloxopen/protoc-gen-gorm/errors"
	gorm1 "github.com/jinzhu/gorm"
	field_mask1 "google.golang.org/genproto/protobuf/field_mask"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = fmt.Errorf
var _ = math.Inf

type GovernancePrepProcessedORM struct {
	Address string `gorm:"primary_key"`
	IsPrep  bool
}

// TableName overrides the default tablename generated by GORM
func (GovernancePrepProcessedORM) TableName() string {
	return "governance_prep_processeds"
}

// ToORM runs the BeforeToORM hook if present, converts the fields of this
// object to ORM format, runs the AfterToORM hook, then returns the ORM object
func (m *GovernancePrepProcessed) ToORM(ctx context.Context) (GovernancePrepProcessedORM, error) {
	to := GovernancePrepProcessedORM{}
	var err error
	if prehook, ok := interface{}(m).(GovernancePrepProcessedWithBeforeToORM); ok {
		if err = prehook.BeforeToORM(ctx, &to); err != nil {
			return to, err
		}
	}
	to.Address = m.Address
	to.IsPrep = m.IsPrep
	if posthook, ok := interface{}(m).(GovernancePrepProcessedWithAfterToORM); ok {
		err = posthook.AfterToORM(ctx, &to)
	}
	return to, err
}

// ToPB runs the BeforeToPB hook if present, converts the fields of this
// object to PB format, runs the AfterToPB hook, then returns the PB object
func (m *GovernancePrepProcessedORM) ToPB(ctx context.Context) (GovernancePrepProcessed, error) {
	to := GovernancePrepProcessed{}
	var err error
	if prehook, ok := interface{}(m).(GovernancePrepProcessedWithBeforeToPB); ok {
		if err = prehook.BeforeToPB(ctx, &to); err != nil {
			return to, err
		}
	}
	to.Address = m.Address
	to.IsPrep = m.IsPrep
	if posthook, ok := interface{}(m).(GovernancePrepProcessedWithAfterToPB); ok {
		err = posthook.AfterToPB(ctx, &to)
	}
	return to, err
}

// The following are interfaces you can implement for special behavior during ORM/PB conversions
// of type GovernancePrepProcessed the arg will be the target, the caller the one being converted from

// GovernancePrepProcessedBeforeToORM called before default ToORM code
type GovernancePrepProcessedWithBeforeToORM interface {
	BeforeToORM(context.Context, *GovernancePrepProcessedORM) error
}

// GovernancePrepProcessedAfterToORM called after default ToORM code
type GovernancePrepProcessedWithAfterToORM interface {
	AfterToORM(context.Context, *GovernancePrepProcessedORM) error
}

// GovernancePrepProcessedBeforeToPB called before default ToPB code
type GovernancePrepProcessedWithBeforeToPB interface {
	BeforeToPB(context.Context, *GovernancePrepProcessed) error
}

// GovernancePrepProcessedAfterToPB called after default ToPB code
type GovernancePrepProcessedWithAfterToPB interface {
	AfterToPB(context.Context, *GovernancePrepProcessed) error
}

// DefaultCreateGovernancePrepProcessed executes a basic gorm create call
func DefaultCreateGovernancePrepProcessed(ctx context.Context, in *GovernancePrepProcessed, db *gorm1.DB) (*GovernancePrepProcessed, error) {
	if in == nil {
		return nil, errors1.NilArgumentError
	}
	ormObj, err := in.ToORM(ctx)
	if err != nil {
		return nil, err
	}
	if hook, ok := interface{}(&ormObj).(GovernancePrepProcessedORMWithBeforeCreate_); ok {
		if db, err = hook.BeforeCreate_(ctx, db); err != nil {
			return nil, err
		}
	}
	if err = db.Create(&ormObj).Error; err != nil {
		return nil, err
	}
	if hook, ok := interface{}(&ormObj).(GovernancePrepProcessedORMWithAfterCreate_); ok {
		if err = hook.AfterCreate_(ctx, db); err != nil {
			return nil, err
		}
	}
	pbResponse, err := ormObj.ToPB(ctx)
	return &pbResponse, err
}

type GovernancePrepProcessedORMWithBeforeCreate_ interface {
	BeforeCreate_(context.Context, *gorm1.DB) (*gorm1.DB, error)
}
type GovernancePrepProcessedORMWithAfterCreate_ interface {
	AfterCreate_(context.Context, *gorm1.DB) error
}

// DefaultApplyFieldMaskGovernancePrepProcessed patches an pbObject with patcher according to a field mask.
func DefaultApplyFieldMaskGovernancePrepProcessed(ctx context.Context, patchee *GovernancePrepProcessed, patcher *GovernancePrepProcessed, updateMask *field_mask1.FieldMask, prefix string, db *gorm1.DB) (*GovernancePrepProcessed, error) {
	if patcher == nil {
		return nil, nil
	} else if patchee == nil {
		return nil, errors1.NilArgumentError
	}
	var err error
	for _, f := range updateMask.Paths {
		if f == prefix+"Address" {
			patchee.Address = patcher.Address
			continue
		}
		if f == prefix+"IsPrep" {
			patchee.IsPrep = patcher.IsPrep
			continue
		}
	}
	if err != nil {
		return nil, err
	}
	return patchee, nil
}

// DefaultListGovernancePrepProcessed executes a gorm list call
func DefaultListGovernancePrepProcessed(ctx context.Context, db *gorm1.DB) ([]*GovernancePrepProcessed, error) {
	in := GovernancePrepProcessed{}
	ormObj, err := in.ToORM(ctx)
	if err != nil {
		return nil, err
	}
	if hook, ok := interface{}(&ormObj).(GovernancePrepProcessedORMWithBeforeListApplyQuery); ok {
		if db, err = hook.BeforeListApplyQuery(ctx, db); err != nil {
			return nil, err
		}
	}
	db, err = gorm2.ApplyCollectionOperators(ctx, db, &GovernancePrepProcessedORM{}, &GovernancePrepProcessed{}, nil, nil, nil, nil)
	if err != nil {
		return nil, err
	}
	if hook, ok := interface{}(&ormObj).(GovernancePrepProcessedORMWithBeforeListFind); ok {
		if db, err = hook.BeforeListFind(ctx, db); err != nil {
			return nil, err
		}
	}
	db = db.Where(&ormObj)
	db = db.Order("address")
	ormResponse := []GovernancePrepProcessedORM{}
	if err := db.Find(&ormResponse).Error; err != nil {
		return nil, err
	}
	if hook, ok := interface{}(&ormObj).(GovernancePrepProcessedORMWithAfterListFind); ok {
		if err = hook.AfterListFind(ctx, db, &ormResponse); err != nil {
			return nil, err
		}
	}
	pbResponse := []*GovernancePrepProcessed{}
	for _, responseEntry := range ormResponse {
		temp, err := responseEntry.ToPB(ctx)
		if err != nil {
			return nil, err
		}
		pbResponse = append(pbResponse, &temp)
	}
	return pbResponse, nil
}

type GovernancePrepProcessedORMWithBeforeListApplyQuery interface {
	BeforeListApplyQuery(context.Context, *gorm1.DB) (*gorm1.DB, error)
}
type GovernancePrepProcessedORMWithBeforeListFind interface {
	BeforeListFind(context.Context, *gorm1.DB) (*gorm1.DB, error)
}
type GovernancePrepProcessedORMWithAfterListFind interface {
	AfterListFind(context.Context, *gorm1.DB, *[]GovernancePrepProcessedORM) error
}
