// Code generated by protoc-gen-gogo. DO NOT EDIT.
// source: log_count_by_public_key_index.proto

package models

import (
	context "context"
	fmt "fmt"
	
	_ "github.com/infobloxopen/protoc-gen-gorm/options"
	math "math"

	gorm2 "github.com/infobloxopen/atlas-app-toolkit/gorm"
	errors1 "github.com/infobloxopen/protoc-gen-gorm/errors"
	gorm1 "github.com/jinzhu/gorm"
	field_mask1 "google.golang.org/genproto/protobuf/field_mask"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = fmt.Errorf
var _ = math.Inf

type LogCountByPublicKeyIndexORM struct {
	LogIndex        uint64 `gorm:"primary_key"`
	PublicKey       string `gorm:"primary_key"`
	TransactionHash string `gorm:"primary_key"`
}

// TableName overrides the default tablename generated by GORM
func (LogCountByPublicKeyIndexORM) TableName() string {
	return "log_count_by_public_key_indices"
}

// ToORM runs the BeforeToORM hook if present, converts the fields of this
// object to ORM format, runs the AfterToORM hook, then returns the ORM object
func (m *LogCountByPublicKeyIndex) ToORM(ctx context.Context) (LogCountByPublicKeyIndexORM, error) {
	to := LogCountByPublicKeyIndexORM{}
	var err error
	if prehook, ok := interface{}(m).(LogCountByPublicKeyIndexWithBeforeToORM); ok {
		if err = prehook.BeforeToORM(ctx, &to); err != nil {
			return to, err
		}
	}
	to.TransactionHash = m.TransactionHash
	to.LogIndex = m.LogIndex
	to.PublicKey = m.PublicKey
	if posthook, ok := interface{}(m).(LogCountByPublicKeyIndexWithAfterToORM); ok {
		err = posthook.AfterToORM(ctx, &to)
	}
	return to, err
}

// ToPB runs the BeforeToPB hook if present, converts the fields of this
// object to PB format, runs the AfterToPB hook, then returns the PB object
func (m *LogCountByPublicKeyIndexORM) ToPB(ctx context.Context) (LogCountByPublicKeyIndex, error) {
	to := LogCountByPublicKeyIndex{}
	var err error
	if prehook, ok := interface{}(m).(LogCountByPublicKeyIndexWithBeforeToPB); ok {
		if err = prehook.BeforeToPB(ctx, &to); err != nil {
			return to, err
		}
	}
	to.TransactionHash = m.TransactionHash
	to.LogIndex = m.LogIndex
	to.PublicKey = m.PublicKey
	if posthook, ok := interface{}(m).(LogCountByPublicKeyIndexWithAfterToPB); ok {
		err = posthook.AfterToPB(ctx, &to)
	}
	return to, err
}

// The following are interfaces you can implement for special behavior during ORM/PB conversions
// of type LogCountByPublicKeyIndex the arg will be the target, the caller the one being converted from

// LogCountByPublicKeyIndexBeforeToORM called before default ToORM code
type LogCountByPublicKeyIndexWithBeforeToORM interface {
	BeforeToORM(context.Context, *LogCountByPublicKeyIndexORM) error
}

// LogCountByPublicKeyIndexAfterToORM called after default ToORM code
type LogCountByPublicKeyIndexWithAfterToORM interface {
	AfterToORM(context.Context, *LogCountByPublicKeyIndexORM) error
}

// LogCountByPublicKeyIndexBeforeToPB called before default ToPB code
type LogCountByPublicKeyIndexWithBeforeToPB interface {
	BeforeToPB(context.Context, *LogCountByPublicKeyIndex) error
}

// LogCountByPublicKeyIndexAfterToPB called after default ToPB code
type LogCountByPublicKeyIndexWithAfterToPB interface {
	AfterToPB(context.Context, *LogCountByPublicKeyIndex) error
}

// DefaultCreateLogCountByPublicKeyIndex executes a basic gorm create call
func DefaultCreateLogCountByPublicKeyIndex(ctx context.Context, in *LogCountByPublicKeyIndex, db *gorm1.DB) (*LogCountByPublicKeyIndex, error) {
	if in == nil {
		return nil, errors1.NilArgumentError
	}
	ormObj, err := in.ToORM(ctx)
	if err != nil {
		return nil, err
	}
	if hook, ok := interface{}(&ormObj).(LogCountByPublicKeyIndexORMWithBeforeCreate_); ok {
		if db, err = hook.BeforeCreate_(ctx, db); err != nil {
			return nil, err
		}
	}
	if err = db.Create(&ormObj).Error; err != nil {
		return nil, err
	}
	if hook, ok := interface{}(&ormObj).(LogCountByPublicKeyIndexORMWithAfterCreate_); ok {
		if err = hook.AfterCreate_(ctx, db); err != nil {
			return nil, err
		}
	}
	pbResponse, err := ormObj.ToPB(ctx)
	return &pbResponse, err
}

type LogCountByPublicKeyIndexORMWithBeforeCreate_ interface {
	BeforeCreate_(context.Context, *gorm1.DB) (*gorm1.DB, error)
}
type LogCountByPublicKeyIndexORMWithAfterCreate_ interface {
	AfterCreate_(context.Context, *gorm1.DB) error
}

// DefaultApplyFieldMaskLogCountByPublicKeyIndex patches an pbObject with patcher according to a field mask.
func DefaultApplyFieldMaskLogCountByPublicKeyIndex(ctx context.Context, patchee *LogCountByPublicKeyIndex, patcher *LogCountByPublicKeyIndex, updateMask *field_mask1.FieldMask, prefix string, db *gorm1.DB) (*LogCountByPublicKeyIndex, error) {
	if patcher == nil {
		return nil, nil
	} else if patchee == nil {
		return nil, errors1.NilArgumentError
	}
	var err error
	for _, f := range updateMask.Paths {
		if f == prefix+"TransactionHash" {
			patchee.TransactionHash = patcher.TransactionHash
			continue
		}
		if f == prefix+"LogIndex" {
			patchee.LogIndex = patcher.LogIndex
			continue
		}
		if f == prefix+"PublicKey" {
			patchee.PublicKey = patcher.PublicKey
			continue
		}
	}
	if err != nil {
		return nil, err
	}
	return patchee, nil
}

// DefaultListLogCountByPublicKeyIndex executes a gorm list call
func DefaultListLogCountByPublicKeyIndex(ctx context.Context, db *gorm1.DB) ([]*LogCountByPublicKeyIndex, error) {
	in := LogCountByPublicKeyIndex{}
	ormObj, err := in.ToORM(ctx)
	if err != nil {
		return nil, err
	}
	if hook, ok := interface{}(&ormObj).(LogCountByPublicKeyIndexORMWithBeforeListApplyQuery); ok {
		if db, err = hook.BeforeListApplyQuery(ctx, db); err != nil {
			return nil, err
		}
	}
	db, err = gorm2.ApplyCollectionOperators(ctx, db, &LogCountByPublicKeyIndexORM{}, &LogCountByPublicKeyIndex{}, nil, nil, nil, nil)
	if err != nil {
		return nil, err
	}
	if hook, ok := interface{}(&ormObj).(LogCountByPublicKeyIndexORMWithBeforeListFind); ok {
		if db, err = hook.BeforeListFind(ctx, db); err != nil {
			return nil, err
		}
	}
	db = db.Where(&ormObj)
	db = db.Order("transaction_hash")
	ormResponse := []LogCountByPublicKeyIndexORM{}
	if err := db.Find(&ormResponse).Error; err != nil {
		return nil, err
	}
	if hook, ok := interface{}(&ormObj).(LogCountByPublicKeyIndexORMWithAfterListFind); ok {
		if err = hook.AfterListFind(ctx, db, &ormResponse); err != nil {
			return nil, err
		}
	}
	pbResponse := []*LogCountByPublicKeyIndex{}
	for _, responseEntry := range ormResponse {
		temp, err := responseEntry.ToPB(ctx)
		if err != nil {
			return nil, err
		}
		pbResponse = append(pbResponse, &temp)
	}
	return pbResponse, nil
}

type LogCountByPublicKeyIndexORMWithBeforeListApplyQuery interface {
	BeforeListApplyQuery(context.Context, *gorm1.DB) (*gorm1.DB, error)
}
type LogCountByPublicKeyIndexORMWithBeforeListFind interface {
	BeforeListFind(context.Context, *gorm1.DB) (*gorm1.DB, error)
}
type LogCountByPublicKeyIndexORMWithAfterListFind interface {
	AfterListFind(context.Context, *gorm1.DB, *[]LogCountByPublicKeyIndexORM) error
}
