// Code generated by protoc-gen-gogo. DO NOT EDIT.
// source: log_count_by_block_number.proto

package models

import (
	context "context"
	fmt "fmt"
	
	_ "github.com/infobloxopen/protoc-gen-gorm/options"
	math "math"

	gorm2 "github.com/infobloxopen/atlas-app-toolkit/gorm"
	errors1 "github.com/infobloxopen/protoc-gen-gorm/errors"
	gorm1 "github.com/jinzhu/gorm"
	field_mask1 "google.golang.org/genproto/protobuf/field_mask"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = fmt.Errorf
var _ = math.Inf

type LogCountByBlockNumberORM struct {
	BlockNumber           uint64 `gorm:"index:log_count_by_block_count_idx_block_count"`
	Count                 uint32 `gorm:"index:log_count_by_block_count_idx_count"`
	LogIndex              uint64 `gorm:"primary_key"`
	MaxCountByTransaction uint32
	TransactionHash       string `gorm:"primary_key"`
}

// TableName overrides the default tablename generated by GORM
func (LogCountByBlockNumberORM) TableName() string {
	return "log_count_by_block_numbers"
}

// ToORM runs the BeforeToORM hook if present, converts the fields of this
// object to ORM format, runs the AfterToORM hook, then returns the ORM object
func (m *LogCountByBlockNumber) ToORM(ctx context.Context) (LogCountByBlockNumberORM, error) {
	to := LogCountByBlockNumberORM{}
	var err error
	if prehook, ok := interface{}(m).(LogCountByBlockNumberWithBeforeToORM); ok {
		if err = prehook.BeforeToORM(ctx, &to); err != nil {
			return to, err
		}
	}
	to.TransactionHash = m.TransactionHash
	to.LogIndex = m.LogIndex
	to.BlockNumber = m.BlockNumber
	to.Count = m.Count
	to.MaxCountByTransaction = m.MaxCountByTransaction
	if posthook, ok := interface{}(m).(LogCountByBlockNumberWithAfterToORM); ok {
		err = posthook.AfterToORM(ctx, &to)
	}
	return to, err
}

// ToPB runs the BeforeToPB hook if present, converts the fields of this
// object to PB format, runs the AfterToPB hook, then returns the PB object
func (m *LogCountByBlockNumberORM) ToPB(ctx context.Context) (LogCountByBlockNumber, error) {
	to := LogCountByBlockNumber{}
	var err error
	if prehook, ok := interface{}(m).(LogCountByBlockNumberWithBeforeToPB); ok {
		if err = prehook.BeforeToPB(ctx, &to); err != nil {
			return to, err
		}
	}
	to.TransactionHash = m.TransactionHash
	to.LogIndex = m.LogIndex
	to.BlockNumber = m.BlockNumber
	to.Count = m.Count
	to.MaxCountByTransaction = m.MaxCountByTransaction
	if posthook, ok := interface{}(m).(LogCountByBlockNumberWithAfterToPB); ok {
		err = posthook.AfterToPB(ctx, &to)
	}
	return to, err
}

// The following are interfaces you can implement for special behavior during ORM/PB conversions
// of type LogCountByBlockNumber the arg will be the target, the caller the one being converted from

// LogCountByBlockNumberBeforeToORM called before default ToORM code
type LogCountByBlockNumberWithBeforeToORM interface {
	BeforeToORM(context.Context, *LogCountByBlockNumberORM) error
}

// LogCountByBlockNumberAfterToORM called after default ToORM code
type LogCountByBlockNumberWithAfterToORM interface {
	AfterToORM(context.Context, *LogCountByBlockNumberORM) error
}

// LogCountByBlockNumberBeforeToPB called before default ToPB code
type LogCountByBlockNumberWithBeforeToPB interface {
	BeforeToPB(context.Context, *LogCountByBlockNumber) error
}

// LogCountByBlockNumberAfterToPB called after default ToPB code
type LogCountByBlockNumberWithAfterToPB interface {
	AfterToPB(context.Context, *LogCountByBlockNumber) error
}

// DefaultCreateLogCountByBlockNumber executes a basic gorm create call
func DefaultCreateLogCountByBlockNumber(ctx context.Context, in *LogCountByBlockNumber, db *gorm1.DB) (*LogCountByBlockNumber, error) {
	if in == nil {
		return nil, errors1.NilArgumentError
	}
	ormObj, err := in.ToORM(ctx)
	if err != nil {
		return nil, err
	}
	if hook, ok := interface{}(&ormObj).(LogCountByBlockNumberORMWithBeforeCreate_); ok {
		if db, err = hook.BeforeCreate_(ctx, db); err != nil {
			return nil, err
		}
	}
	if err = db.Create(&ormObj).Error; err != nil {
		return nil, err
	}
	if hook, ok := interface{}(&ormObj).(LogCountByBlockNumberORMWithAfterCreate_); ok {
		if err = hook.AfterCreate_(ctx, db); err != nil {
			return nil, err
		}
	}
	pbResponse, err := ormObj.ToPB(ctx)
	return &pbResponse, err
}

type LogCountByBlockNumberORMWithBeforeCreate_ interface {
	BeforeCreate_(context.Context, *gorm1.DB) (*gorm1.DB, error)
}
type LogCountByBlockNumberORMWithAfterCreate_ interface {
	AfterCreate_(context.Context, *gorm1.DB) error
}

// DefaultApplyFieldMaskLogCountByBlockNumber patches an pbObject with patcher according to a field mask.
func DefaultApplyFieldMaskLogCountByBlockNumber(ctx context.Context, patchee *LogCountByBlockNumber, patcher *LogCountByBlockNumber, updateMask *field_mask1.FieldMask, prefix string, db *gorm1.DB) (*LogCountByBlockNumber, error) {
	if patcher == nil {
		return nil, nil
	} else if patchee == nil {
		return nil, errors1.NilArgumentError
	}
	var err error
	for _, f := range updateMask.Paths {
		if f == prefix+"TransactionHash" {
			patchee.TransactionHash = patcher.TransactionHash
			continue
		}
		if f == prefix+"LogIndex" {
			patchee.LogIndex = patcher.LogIndex
			continue
		}
		if f == prefix+"BlockNumber" {
			patchee.BlockNumber = patcher.BlockNumber
			continue
		}
		if f == prefix+"Count" {
			patchee.Count = patcher.Count
			continue
		}
		if f == prefix+"MaxCountByTransaction" {
			patchee.MaxCountByTransaction = patcher.MaxCountByTransaction
			continue
		}
	}
	if err != nil {
		return nil, err
	}
	return patchee, nil
}

// DefaultListLogCountByBlockNumber executes a gorm list call
func DefaultListLogCountByBlockNumber(ctx context.Context, db *gorm1.DB) ([]*LogCountByBlockNumber, error) {
	in := LogCountByBlockNumber{}
	ormObj, err := in.ToORM(ctx)
	if err != nil {
		return nil, err
	}
	if hook, ok := interface{}(&ormObj).(LogCountByBlockNumberORMWithBeforeListApplyQuery); ok {
		if db, err = hook.BeforeListApplyQuery(ctx, db); err != nil {
			return nil, err
		}
	}
	db, err = gorm2.ApplyCollectionOperators(ctx, db, &LogCountByBlockNumberORM{}, &LogCountByBlockNumber{}, nil, nil, nil, nil)
	if err != nil {
		return nil, err
	}
	if hook, ok := interface{}(&ormObj).(LogCountByBlockNumberORMWithBeforeListFind); ok {
		if db, err = hook.BeforeListFind(ctx, db); err != nil {
			return nil, err
		}
	}
	db = db.Where(&ormObj)
	db = db.Order("log_index")
	ormResponse := []LogCountByBlockNumberORM{}
	if err := db.Find(&ormResponse).Error; err != nil {
		return nil, err
	}
	if hook, ok := interface{}(&ormObj).(LogCountByBlockNumberORMWithAfterListFind); ok {
		if err = hook.AfterListFind(ctx, db, &ormResponse); err != nil {
			return nil, err
		}
	}
	pbResponse := []*LogCountByBlockNumber{}
	for _, responseEntry := range ormResponse {
		temp, err := responseEntry.ToPB(ctx)
		if err != nil {
			return nil, err
		}
		pbResponse = append(pbResponse, &temp)
	}
	return pbResponse, nil
}

type LogCountByBlockNumberORMWithBeforeListApplyQuery interface {
	BeforeListApplyQuery(context.Context, *gorm1.DB) (*gorm1.DB, error)
}
type LogCountByBlockNumberORMWithBeforeListFind interface {
	BeforeListFind(context.Context, *gorm1.DB) (*gorm1.DB, error)
}
type LogCountByBlockNumberORMWithAfterListFind interface {
	AfterListFind(context.Context, *gorm1.DB, *[]LogCountByBlockNumberORM) error
}
