// Code generated by protoc-gen-gogo. DO NOT EDIT.
// source: transaction_count_by_block_number.proto

package models

import (
	context "context"
	fmt "fmt"
	
	_ "github.com/infobloxopen/protoc-gen-gorm/options"
	math "math"

	gorm2 "github.com/infobloxopen/atlas-app-toolkit/gorm"
	errors1 "github.com/infobloxopen/protoc-gen-gorm/errors"
	gorm1 "github.com/jinzhu/gorm"
	field_mask1 "google.golang.org/genproto/protobuf/field_mask"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = fmt.Errorf
var _ = math.Inf

type TransactionCountByBlockNumberORM struct {
	BlockNumber     uint64 `gorm:"index:transaction_count_by_block_count_idx_block_count"`
	Count           uint32
	TransactionHash string `gorm:"primary_key"`
}

// TableName overrides the default tablename generated by GORM
func (TransactionCountByBlockNumberORM) TableName() string {
	return "transaction_count_by_block_numbers"
}

// ToORM runs the BeforeToORM hook if present, converts the fields of this
// object to ORM format, runs the AfterToORM hook, then returns the ORM object
func (m *TransactionCountByBlockNumber) ToORM(ctx context.Context) (TransactionCountByBlockNumberORM, error) {
	to := TransactionCountByBlockNumberORM{}
	var err error
	if prehook, ok := interface{}(m).(TransactionCountByBlockNumberWithBeforeToORM); ok {
		if err = prehook.BeforeToORM(ctx, &to); err != nil {
			return to, err
		}
	}
	to.TransactionHash = m.TransactionHash
	to.BlockNumber = m.BlockNumber
	to.Count = m.Count
	if posthook, ok := interface{}(m).(TransactionCountByBlockNumberWithAfterToORM); ok {
		err = posthook.AfterToORM(ctx, &to)
	}
	return to, err
}

// ToPB runs the BeforeToPB hook if present, converts the fields of this
// object to PB format, runs the AfterToPB hook, then returns the PB object
func (m *TransactionCountByBlockNumberORM) ToPB(ctx context.Context) (TransactionCountByBlockNumber, error) {
	to := TransactionCountByBlockNumber{}
	var err error
	if prehook, ok := interface{}(m).(TransactionCountByBlockNumberWithBeforeToPB); ok {
		if err = prehook.BeforeToPB(ctx, &to); err != nil {
			return to, err
		}
	}
	to.TransactionHash = m.TransactionHash
	to.BlockNumber = m.BlockNumber
	to.Count = m.Count
	if posthook, ok := interface{}(m).(TransactionCountByBlockNumberWithAfterToPB); ok {
		err = posthook.AfterToPB(ctx, &to)
	}
	return to, err
}

// The following are interfaces you can implement for special behavior during ORM/PB conversions
// of type TransactionCountByBlockNumber the arg will be the target, the caller the one being converted from

// TransactionCountByBlockNumberBeforeToORM called before default ToORM code
type TransactionCountByBlockNumberWithBeforeToORM interface {
	BeforeToORM(context.Context, *TransactionCountByBlockNumberORM) error
}

// TransactionCountByBlockNumberAfterToORM called after default ToORM code
type TransactionCountByBlockNumberWithAfterToORM interface {
	AfterToORM(context.Context, *TransactionCountByBlockNumberORM) error
}

// TransactionCountByBlockNumberBeforeToPB called before default ToPB code
type TransactionCountByBlockNumberWithBeforeToPB interface {
	BeforeToPB(context.Context, *TransactionCountByBlockNumber) error
}

// TransactionCountByBlockNumberAfterToPB called after default ToPB code
type TransactionCountByBlockNumberWithAfterToPB interface {
	AfterToPB(context.Context, *TransactionCountByBlockNumber) error
}

// DefaultCreateTransactionCountByBlockNumber executes a basic gorm create call
func DefaultCreateTransactionCountByBlockNumber(ctx context.Context, in *TransactionCountByBlockNumber, db *gorm1.DB) (*TransactionCountByBlockNumber, error) {
	if in == nil {
		return nil, errors1.NilArgumentError
	}
	ormObj, err := in.ToORM(ctx)
	if err != nil {
		return nil, err
	}
	if hook, ok := interface{}(&ormObj).(TransactionCountByBlockNumberORMWithBeforeCreate_); ok {
		if db, err = hook.BeforeCreate_(ctx, db); err != nil {
			return nil, err
		}
	}
	if err = db.Create(&ormObj).Error; err != nil {
		return nil, err
	}
	if hook, ok := interface{}(&ormObj).(TransactionCountByBlockNumberORMWithAfterCreate_); ok {
		if err = hook.AfterCreate_(ctx, db); err != nil {
			return nil, err
		}
	}
	pbResponse, err := ormObj.ToPB(ctx)
	return &pbResponse, err
}

type TransactionCountByBlockNumberORMWithBeforeCreate_ interface {
	BeforeCreate_(context.Context, *gorm1.DB) (*gorm1.DB, error)
}
type TransactionCountByBlockNumberORMWithAfterCreate_ interface {
	AfterCreate_(context.Context, *gorm1.DB) error
}

// DefaultApplyFieldMaskTransactionCountByBlockNumber patches an pbObject with patcher according to a field mask.
func DefaultApplyFieldMaskTransactionCountByBlockNumber(ctx context.Context, patchee *TransactionCountByBlockNumber, patcher *TransactionCountByBlockNumber, updateMask *field_mask1.FieldMask, prefix string, db *gorm1.DB) (*TransactionCountByBlockNumber, error) {
	if patcher == nil {
		return nil, nil
	} else if patchee == nil {
		return nil, errors1.NilArgumentError
	}
	var err error
	for _, f := range updateMask.Paths {
		if f == prefix+"TransactionHash" {
			patchee.TransactionHash = patcher.TransactionHash
			continue
		}
		if f == prefix+"BlockNumber" {
			patchee.BlockNumber = patcher.BlockNumber
			continue
		}
		if f == prefix+"Count" {
			patchee.Count = patcher.Count
			continue
		}
	}
	if err != nil {
		return nil, err
	}
	return patchee, nil
}

// DefaultListTransactionCountByBlockNumber executes a gorm list call
func DefaultListTransactionCountByBlockNumber(ctx context.Context, db *gorm1.DB) ([]*TransactionCountByBlockNumber, error) {
	in := TransactionCountByBlockNumber{}
	ormObj, err := in.ToORM(ctx)
	if err != nil {
		return nil, err
	}
	if hook, ok := interface{}(&ormObj).(TransactionCountByBlockNumberORMWithBeforeListApplyQuery); ok {
		if db, err = hook.BeforeListApplyQuery(ctx, db); err != nil {
			return nil, err
		}
	}
	db, err = gorm2.ApplyCollectionOperators(ctx, db, &TransactionCountByBlockNumberORM{}, &TransactionCountByBlockNumber{}, nil, nil, nil, nil)
	if err != nil {
		return nil, err
	}
	if hook, ok := interface{}(&ormObj).(TransactionCountByBlockNumberORMWithBeforeListFind); ok {
		if db, err = hook.BeforeListFind(ctx, db); err != nil {
			return nil, err
		}
	}
	db = db.Where(&ormObj)
	db = db.Order("transaction_hash")
	ormResponse := []TransactionCountByBlockNumberORM{}
	if err := db.Find(&ormResponse).Error; err != nil {
		return nil, err
	}
	if hook, ok := interface{}(&ormObj).(TransactionCountByBlockNumberORMWithAfterListFind); ok {
		if err = hook.AfterListFind(ctx, db, &ormResponse); err != nil {
			return nil, err
		}
	}
	pbResponse := []*TransactionCountByBlockNumber{}
	for _, responseEntry := range ormResponse {
		temp, err := responseEntry.ToPB(ctx)
		if err != nil {
			return nil, err
		}
		pbResponse = append(pbResponse, &temp)
	}
	return pbResponse, nil
}

type TransactionCountByBlockNumberORMWithBeforeListApplyQuery interface {
	BeforeListApplyQuery(context.Context, *gorm1.DB) (*gorm1.DB, error)
}
type TransactionCountByBlockNumberORMWithBeforeListFind interface {
	BeforeListFind(context.Context, *gorm1.DB) (*gorm1.DB, error)
}
type TransactionCountByBlockNumberORMWithAfterListFind interface {
	AfterListFind(context.Context, *gorm1.DB, *[]TransactionCountByBlockNumberORM) error
}
